Map<String, String> assistedEquipmentImages = {
  "band": "assets/images/band.png",
  "barbell": "assets/images/barble.png",
  "body weight": "assets/images/pull-up.png",
  "bosu ball": "assets/images/bosu_ball.png",
  "cable": "assets/images/band.png",
  "dumbbell": "assets/images/gym.png",
  "elliptical machine": "assets/images/elliptical_machine.png",
  "ez barbell": "assets/images/ez_barbell.png",
  "hammer": "assets/images/hammer.png",
  "kettlebell": "assets/images/kettlebell.png",
  "leverage machine": "assets/images/leverage_machine.png",
  "medicine ball": "assets/images/medicine_ball.png",
  "olympic barbell": "assets/images/olympic_barbell.png",
  "resistance band": "assets/images/resistance_band.png",
  "roller": "assets/images/roller.png",
  "rope": "assets/images/rope.png",
  "skierg machine": "assets/images/skierg_machine.png",
  "sled machine": "assets/images/sled_machine.png",
  "smith machine": "assets/images/smith_machine.png",
  "stability ball": "assets/images/stability_ball.png",
  "stationary bike": "assets/images/stationary_bike.png",
  "stepmill machine": "assets/images/stepmill_machine.jpeg",
  "tire": "assets/images/tire.png",
  "trap bar": "assets/images/trap_bar.png",
  "upper body ergometer": "assets/images/upper_body_ergometer.png",
  "weighted": "assets/images/weighted.png",
  "wheel roller": "assets/images/wheel_roller.webp",
};

Map<String, String> bodyPartsImages = {
  "back": "assets/images/back.png",
  "cardio": "assets/images/cardio.png",
  "chest": "assets/images/chest.png",
  "lower arms": "assets/images/lower arms.png",
  "lower legs": "assets/images/ankle.png",
  "neck": "assets/images/neck.png",
  "shoulders": "assets/images/human.png",
  "abductors": "assets/images/abductors.png",
  "abs": "assets/images/abs.png",
  "adductors": "assets/images/adductors.png",
  "biceps": "assets/images/biceps.png",
  "calves": "assets/images/calves.png",
  "cardiovascular system": "assets/images/cardio.png",
  "delts": "assets/images/delts.png",
  "forearms": "assets/images/forearms.png",
  "glutes": "assets/images/glutes.png",
  "hamstrings": "assets/images/lower leg.png",
  "lats": "assets/images/lats.png",
  "levator scapulae": "assets/images/scapula.png",
  "pectorals": "assets/images/pectoral.png",
  "quads": "assets/images/quads.png",
  "serratus anterior": "assets/images/oblique.png",
  "spine": "assets/images/spine.png",
  "traps": "assets/images/upper back.png",
  "triceps": "assets/images/triceps.png",
  "upper back": "assets/images/upper back.png",
  "upper arms": "assets/images/upper_arm.png",
  "upper legs": "assets/images/upper legs.png",
  "waist": "assets/images/waist.png",
};